# Konfigurasi User dan Password
# Format: username = { password = "...", shop_id = 12345 }

[users]
admin = { password = "admin123", shop_id = 1090831790 }
toko_budi = { password = "budi123", shop_id = 234567890 }
toko_siti = { password = "siti456", shop_id = 987654321 }